name: Integration Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    integration:
        uses: apermo/reusable-workflows/.github/workflows/reusable-wp-integration.yml@main
        with:
            php-versions: >-
                ${{ github.event_name == 'push'
                    && '["8.2","8.3","8.4"]'
                    || '["8.2","8.4"]' }}
            wp-versions: '["latest","6.6"]'
            multisite: 'both'
